name: Bump version and tag

on:
  workflow_dispatch:
    inputs:
      versionType:
        description: 'Version type (major, minor, patch)'
        required: true
        default: 'patch'

jobs:
  bump-version-and-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Important for version tagging

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Specify your project's Node.js version

      - name: Bump version
        run: |
          npm version ${{ github.event.inputs.versionType }} --no-git-tag-version
        env:
          CI: true

      - name: Commit version bump
        run: |
          VERSION=$(node -p "require('./package.json').version")
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add package.json
          git commit -m "chore: bump version to $VERSION"
          git tag v$VERSION

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
